#ifndef _THIX_SYSCALL_H
#define _THIX_SYSCALL_H


#define SYS_fork                 0
#define SYS_exec                 1
#define SYS_ustat                2
#define SYS_utime                3
#define SYS_getpid               4
#define SYS_brk                  5
#define SYS_getppid              6
#define SYS_exit                 7
#define SYS_umask                8
#define SYS_fcntl                9
#define SYS_kctrl               10
#define SYS_kill                11
#define SYS_wait                12
#define SYS_pause               13
#define SYS_statfs              14
#define SYS_fstatfs             15
#define SYS_uname               16
#define SYS_stime               17
#define SYS_time                18
#define SYS_times               19
#define SYS_alarm               20
#define SYS_sync                21
#define SYS_chmod               22
#define SYS_open                23
#define SYS_close               24
#define SYS_link                25
#define SYS_unlink              26
#define SYS_mkdir               27
#define SYS_chdir               28
#define SYS_sigend              29
#define SYS_readdir             30
#define SYS_rmdir               31
#define SYS_reboot              32
#define SYS_lseek               33
#define SYS_read                34
#define SYS_write               35
#define SYS_dup                 36
#define SYS_stat                37
#define SYS_fstat               38
#define SYS_dup2                39
#define SYS_mknod               40
#define SYS_pipe                41
#define SYS_setuid              42
#define SYS_setgid              43
#define SYS_getuid              44
#define SYS_geteuid             45
#define SYS_getgid              46
#define SYS_getegid             47
#define SYS_sigpending          48
#define SYS_sigprocmask         49
#define SYS_sigsuspend          50
#define SYS_sigaction           51
#define SYS_chown               52
#define SYS_access              53
#define SYS_getprocinfo         54
#define SYS_getsysinfo          55
#define SYS_ioctl               56
#define SYS_tcsendbreak         57
#define SYS_tcdrain             58
#define SYS_tcflush             59
#define SYS_tcflow              60
#define SYS_tcgetattr           61
#define SYS_tcsetattr           62
#define SYS_getitimer           63
#define SYS_setitimer           64
#define SYS_getrlimit           65
#define SYS_setrlimit           66
#define SYS_getrusage           67
#define SYS_getpriority         68
#define SYS_setpriority         69
#define SYS_mount               70
#define SYS_umount              71
#define SYS_waitpid             72
#define SYS_setsid              73
#define SYS_setpgid             74
#define SYS_getpgrp             75
#define SYS_swapon              76
#define SYS_swapoff             77
#define SYS_select              78
#define SYS_readlink            79
#define SYS_chroot              80
#define SYS_truncate            81
#define SYS_lstat               82
#define SYS_symlink             83
#define SYS_sethostname         84
#define SYS_setdomainname       85
#define SYS_ftruncate           86
#define SYS_fchown              87
#define SYS_fchmod              88


#endif  /* thix/syscall.h */
