/* This file is automatically generated.
   It defines a symbol `__stub_FUNCTION' for each function
   in the C library which is a stub, meaning it will fail
   every time called, usually setting errno to ENOSYS.  */
#define __stub___wait4
#define __stub_accept
#define __stub_bind
#define __stub_chflags
#define __stub_connect
#define __stub_fchdir
#define __stub_fchflags
#define __stub_fexecve
#define __stub_gethostid
#define __stub_getpeername
#define __stub_getsockname
#define __stub_getsockopt
#define __stub_listen
#define __stub_recv
#define __stub_recvfrom
#define __stub_recvmsg
#define __stub_send
#define __stub_sendmsg
#define __stub_sendto
#define __stub_setegid
#define __stub_seteuid
#define __stub_sethostid
#define __stub_setsockopt
#define __stub_shutdown
#define __stub_socket
#define __stub_socketpair
#define __stub_tcgetpgrp
#define __stub_tcsetpgrp
